### ISSUE TITLE
New OOI document review request: 

### ISSUE THREAD

**Issue by mpostol** [AdamBorowiecki/Integration-MQTT-with-ObjectOrintedInternet#1]
Review the document:
[OOI Unsolicited Communication over MQTT](https://github.com/mpostol/OPC-UA-OOI/blob/master/Networking/SemanticData/README_MQTTMapping.md)

**Comment by AdamBorowiecki** [comment]
MQTT description is clear. At last part of article "Qualitry of Service" should be replaced by "Quality of Service"

**Comment by mpostol** [comment]
OK, thanks
